// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: PLA1.flex

import java.util.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class SchemeLexicalAnalyzer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\u10cf\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\10\0\1\1\1\2\1\3\3\2\22\0\1\2\1\4"+
    "\1\5\1\6\3\4\1\0\1\7\1\10\1\4\1\11"+
    "\1\0\1\11\1\12\1\13\12\14\1\4\1\15\4\4"+
    "\1\16\5\4\1\17\15\4\1\17\6\4\1\20\1\21"+
    "\1\22\2\4\1\0\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\2\4\1\31\2\4\1\32\1\33\1\34\1\35"+
    "\1\36\2\4\1\37\1\40\3\4\1\41\2\4\3\0"+
    "\1\4\6\0\1\2\32\0\1\2\u01df\0\1\2\177\0"+
    "\13\2\35\0\2\2\5\0\1\2\57\0\1\2\240\0"+
    "\1\2\377\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\1\4\1\5\1\2\1\6\1\7"+
    "\1\4\1\2\1\1\1\2\1\1\1\10\1\11\6\4"+
    "\1\12\2\0\1\13\2\1\4\0\1\1\1\0\2\1"+
    "\1\0\2\1\5\0\3\1\2\4\1\1\3\4\1\14"+
    "\3\4\11\0\1\4\1\1\1\0\3\1\3\0\1\1"+
    "\1\0\1\1\1\15\1\0\2\1\1\0\1\1\1\0"+
    "\1\1\7\4\5\0\6\1\1\0\1\1\3\4\3\0"+
    "\1\1\1\0\1\1\2\4\1\0\1\1";

  private static int [] zzUnpackAction() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\42\0\104\0\146\0\210\0\252\0\42\0\42"+
    "\0\314\0\356\0\u0110\0\u0132\0\u0154\0\42\0\42\0\u0176"+
    "\0\u0198\0\u01ba\0\u01dc\0\u01fe\0\u0220\0\210\0\u0242\0\210"+
    "\0\42\0\u0264\0\u0286\0\u02a8\0\u02ca\0\u02ec\0\u030e\0\42"+
    "\0\u0330\0\u0352\0\u0374\0\u0396\0\u03b8\0\u03da\0\u03fc\0\u041e"+
    "\0\u0440\0\u0462\0\u0484\0\u04a6\0\u04c8\0\u04ea\0\u050c\0\u052e"+
    "\0\u0550\0\u0572\0\u0594\0\u05b6\0\146\0\u05d8\0\u05fa\0\u061c"+
    "\0\u063e\0\u0660\0\u0682\0\u06a4\0\u06c6\0\u06e8\0\u070a\0\u072c"+
    "\0\u074e\0\42\0\u0770\0\u0792\0\u07b4\0\u07d6\0\u07f8\0\u081a"+
    "\0\u083c\0\u085e\0\u0880\0\u08a2\0\u08c4\0\u041e\0\u08e6\0\u0908"+
    "\0\u092a\0\u094c\0\u096e\0\u0990\0\u09b2\0\u09d4\0\u09f6\0\u0a18"+
    "\0\u0a3a\0\u0a5c\0\u0a7e\0\u0aa0\0\u0ac2\0\u0ae4\0\u0b06\0\u0b28"+
    "\0\u0b4a\0\u0b6c\0\u0b8e\0\u0bb0\0\u0bd2\0\u0bf4\0\u0c16\0\u0c38"+
    "\0\u0c38\0\u0c5a\0\u0c7c\0\u0c9e\0\u0cc0\0\u0ce2\0\u0d04\0\u0d26"+
    "\0\u0d48\0\u0d6a\0\u0d8c\0\u0dae\0\u0dd0\0\u0df2";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\3\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\4\1\13\1\14\1\15\1\4\1\16\1\2"+
    "\1\17\2\20\1\21\1\22\1\23\1\20\1\24\1\25"+
    "\7\4\43\0\3\3\42\0\1\4\4\0\4\4\2\0"+
    "\1\4\3\0\17\4\5\0\1\26\1\27\12\0\1\30"+
    "\37\0\1\31\4\0\1\32\1\0\1\32\1\33\1\31"+
    "\1\33\3\0\1\32\2\0\1\31\1\32\11\0\1\34"+
    "\1\35\1\0\1\36\1\0\1\15\4\0\6\37\1\40"+
    "\22\0\1\41\1\0\1\42\33\0\1\43\2\0\1\34"+
    "\1\42\1\44\1\13\1\0\1\15\4\0\3\45\3\46"+
    "\1\0\1\47\4\0\1\47\3\0\3\50\1\51\4\0"+
    "\1\50\1\52\1\51\3\0\1\51\3\0\17\51\11\0"+
    "\1\40\1\53\1\0\1\54\6\0\6\55\15\0\1\4"+
    "\1\0\1\56\2\0\1\57\1\4\1\60\1\20\1\0"+
    "\1\61\1\4\3\0\6\20\11\4\4\0\1\4\1\0"+
    "\1\56\2\0\1\57\1\4\1\60\1\20\1\0\1\61"+
    "\1\4\3\0\6\20\4\4\1\62\4\4\4\0\1\4"+
    "\1\0\1\56\2\0\1\57\1\4\1\60\1\20\1\0"+
    "\1\61\1\4\3\0\4\20\1\63\1\20\11\4\4\0"+
    "\1\4\1\0\1\56\2\0\1\57\1\4\1\60\1\20"+
    "\1\0\1\61\1\4\3\0\6\20\1\4\1\64\7\4"+
    "\4\0\1\4\4\0\4\4\2\0\1\4\3\0\5\4"+
    "\1\65\11\4\4\0\1\4\4\0\4\4\2\0\1\4"+
    "\3\0\1\66\3\4\1\67\5\4\1\70\4\4\2\0"+
    "\2\30\15\0\1\71\26\0\1\72\41\0\1\73\45\0"+
    "\1\35\1\0\1\36\6\0\6\37\1\40\24\0\1\74"+
    "\33\0\1\75\3\0\1\74\1\76\1\36\6\0\3\37"+
    "\3\77\1\40\1\100\4\0\1\100\10\0\1\101\4\0"+
    "\1\76\1\37\6\0\6\37\1\40\22\0\1\102\35\0"+
    "\1\103\2\0\1\104\2\0\1\42\1\0\1\105\7\0"+
    "\3\47\1\0\1\47\4\0\1\47\10\0\1\43\2\0"+
    "\1\34\1\103\1\44\2\0\1\15\7\0\3\47\1\0"+
    "\1\47\4\0\1\47\16\0\1\106\6\0\6\107\17\0"+
    "\1\56\2\0\1\110\1\0\1\111\1\45\1\0\1\61"+
    "\4\0\6\45\17\0\1\56\2\0\1\112\1\0\1\111"+
    "\1\113\1\0\1\61\4\0\6\45\22\0\1\114\2\0"+
    "\1\115\26\0\2\50\1\116\1\51\4\0\1\50\1\52"+
    "\1\51\3\0\1\51\3\0\17\51\1\0\2\50\1\116"+
    "\1\51\4\0\4\51\2\0\1\51\3\0\17\51\12\0"+
    "\1\117\43\0\1\120\33\0\1\121\3\0\1\120\1\122"+
    "\1\54\6\0\3\55\3\123\1\0\1\124\4\0\1\124"+
    "\10\0\1\125\4\0\1\122\1\55\6\0\6\55\17\0"+
    "\1\56\2\0\1\110\1\0\1\111\2\0\1\61\27\0"+
    "\1\4\4\0\3\4\1\126\2\0\1\4\3\0\6\126"+
    "\11\4\4\0\1\4\4\0\3\4\1\127\2\0\1\4"+
    "\3\0\6\127\11\4\11\0\1\40\2\0\1\55\6\0"+
    "\6\55\15\0\1\4\4\0\4\4\2\0\1\4\3\0"+
    "\11\4\1\130\5\4\4\0\1\4\1\0\1\56\2\0"+
    "\1\57\1\4\1\60\1\20\1\0\1\61\1\4\3\0"+
    "\5\20\1\131\11\4\4\0\1\4\4\0\4\4\2\0"+
    "\1\4\3\0\14\4\1\132\2\4\4\0\1\4\4\0"+
    "\4\4\2\0\1\4\3\0\10\4\1\133\6\4\4\0"+
    "\1\4\4\0\4\4\2\0\1\4\3\0\15\4\1\65"+
    "\1\4\4\0\1\4\4\0\4\4\2\0\1\4\3\0"+
    "\12\4\1\134\4\4\4\0\1\30\6\0\1\30\3\0"+
    "\1\30\3\0\17\30\27\0\1\40\1\0\1\40\34\0"+
    "\1\40\1\0\1\40\6\0\1\40\3\0\1\40\6\0"+
    "\1\135\5\0\1\74\11\0\3\100\1\40\1\100\4\0"+
    "\1\100\10\0\1\75\3\0\1\135\1\76\12\0\3\100"+
    "\1\40\1\100\4\0\1\100\16\0\1\136\6\0\6\136"+
    "\17\0\1\101\2\0\1\137\1\0\1\76\1\37\6\0"+
    "\6\37\1\40\21\0\1\137\2\0\1\140\33\0\1\101"+
    "\4\0\1\76\15\0\1\40\16\0\1\103\2\0\1\104"+
    "\4\0\1\105\7\0\3\47\1\0\1\47\4\0\1\47"+
    "\14\0\1\35\1\0\1\141\14\0\1\40\21\0\1\40"+
    "\1\53\1\0\1\142\33\0\1\143\2\0\1\34\2\0"+
    "\1\106\1\0\1\15\4\0\6\107\17\0\1\144\2\0"+
    "\1\110\2\0\1\107\1\0\1\61\4\0\6\107\25\0"+
    "\1\37\6\0\6\37\1\40\24\0\1\107\6\0\6\107"+
    "\25\0\1\145\6\0\6\37\1\40\16\0\1\56\2\0"+
    "\1\34\1\0\1\111\1\113\1\0\1\15\4\0\6\45"+
    "\25\0\1\115\36\0\1\104\2\0\1\115\1\0\1\105"+
    "\35\0\1\50\35\0\1\146\5\0\1\120\11\0\3\124"+
    "\1\0\1\124\4\0\1\124\10\0\1\121\3\0\1\146"+
    "\1\122\12\0\3\124\1\0\1\124\4\0\1\124\16\0"+
    "\1\147\6\0\6\147\17\0\1\125\2\0\1\150\1\0"+
    "\1\122\1\55\6\0\6\55\22\0\1\150\2\0\1\151"+
    "\33\0\1\125\4\0\1\122\32\0\1\4\1\0\1\101"+
    "\2\0\2\4\1\152\1\126\2\0\1\4\3\0\6\126"+
    "\11\4\4\0\1\4\1\0\1\144\2\0\1\57\2\4"+
    "\1\127\1\0\1\61\1\4\3\0\6\127\11\4\4\0"+
    "\1\4\4\0\4\4\2\0\1\4\3\0\3\4\1\65"+
    "\13\4\4\0\1\4\1\0\1\56\2\0\1\57\1\4"+
    "\1\60\1\20\1\0\1\61\1\4\3\0\6\20\1\153"+
    "\10\4\4\0\1\4\4\0\4\4\2\0\1\4\3\0"+
    "\4\4\1\65\12\4\4\0\1\4\4\0\4\4\2\0"+
    "\1\4\3\0\1\4\1\154\15\4\4\0\1\4\4\0"+
    "\4\4\2\0\1\4\3\0\13\4\1\65\3\4\6\0"+
    "\1\135\17\0\3\100\1\40\1\100\4\0\1\100\10\0"+
    "\1\155\5\0\1\136\6\0\6\136\1\40\24\0\1\140"+
    "\41\0\1\140\14\0\1\40\16\0\1\156\3\0\1\74"+
    "\1\157\1\141\11\0\3\100\1\40\1\100\4\0\1\100"+
    "\10\0\1\160\3\0\1\120\1\161\1\142\11\0\3\124"+
    "\1\0\1\124\4\0\1\124\10\0\1\143\2\0\1\34"+
    "\4\0\1\15\31\0\1\144\2\0\1\110\4\0\1\61"+
    "\31\0\1\101\2\0\1\104\1\0\1\76\1\145\1\0"+
    "\1\105\4\0\6\37\1\40\16\0\1\146\17\0\3\124"+
    "\1\0\1\124\4\0\1\124\10\0\1\162\5\0\1\147"+
    "\6\0\6\147\25\0\1\151\31\0\1\4\4\0\3\4"+
    "\1\163\2\0\1\4\3\0\6\163\11\4\4\0\1\4"+
    "\4\0\4\4\2\0\1\4\3\0\11\4\1\132\5\4"+
    "\4\0\1\4\4\0\4\4\2\0\1\4\3\0\3\4"+
    "\1\164\13\4\6\0\1\155\22\0\1\40\16\0\1\156"+
    "\3\0\1\135\1\157\12\0\3\100\1\40\1\100\4\0"+
    "\1\100\16\0\1\165\33\0\1\160\3\0\1\146\1\161"+
    "\12\0\3\124\1\0\1\124\4\0\1\124\16\0\1\166"+
    "\33\0\1\162\37\0\1\4\1\0\1\155\2\0\3\4"+
    "\1\163\2\0\1\4\3\0\6\163\11\4\4\0\1\4"+
    "\4\0\4\4\2\0\1\4\3\0\1\65\16\4\6\0"+
    "\1\155\5\0\1\165\14\0\1\40\16\0\1\162\5\0"+
    "\1\166\25\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3604];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\4\1\2\11\5\1\2\11\7\1\2\0"+
    "\1\11\2\1\4\0\1\11\1\0\2\1\1\0\2\1"+
    "\5\0\15\1\11\0\1\11\1\1\1\0\3\1\3\0"+
    "\1\1\1\0\2\1\1\0\2\1\1\0\1\1\1\0"+
    "\10\1\5\0\6\1\1\0\4\1\3\0\1\1\1\0"+
    "\3\1\1\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public SchemeLexicalAnalyzer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("Number: " + yytext());
            }
            // fall through
          case 14: break;
          case 2:
            { System.out.print(yytext());
            }
            // fall through
          case 15: break;
          case 3:
            { 
            }
            // fall through
          case 16: break;
          case 4:
            { System.out.println("Identifier: " + yytext());
            }
            // fall through
          case 17: break;
          case 5:
            { System.out.println("QuotationMark: " + yytext());
            }
            // fall through
          case 18: break;
          case 6:
            { System.out.println("Left Parenthesis: " + yytext());
            }
            // fall through
          case 19: break;
          case 7:
            { System.out.println("Right Parenthesis: " + yytext());
            }
            // fall through
          case 20: break;
          case 8:
            { System.out.println("Left Bracket: " + yytext());
            }
            // fall through
          case 21: break;
          case 9:
            { System.out.println("Right Bracket: " + yytext());
            }
            // fall through
          case 22: break;
          case 10:
            { System.out.println("String: " + yytext());
            }
            // fall through
          case 23: break;
          case 11:
            { System.out.println("Boolean: " + yytext());
            }
            // fall through
          case 24: break;
          case 12:
            { System.out.println("Keyword: " + yytext());
            }
            // fall through
          case 25: break;
          case 13:
            { System.out.println("Comment: " + yytext());
            }
            // fall through
          case 26: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java SchemeLexicalAnalyzer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        SchemeLexicalAnalyzer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new SchemeLexicalAnalyzer(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
